title: Yogeswari Narayasamy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A continuous and curious learner. 
  <br><br>
  An ex-software developer with a passion for technology & writing seeking opportunities to return to coding
  <br><br>
  <a href="https://www.linkedin.com/in/yogeswarinarayasamy/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-142523611-1 # your Google Analytics tracking ID here

