title: Yogeswari Narayasamy # your name (or website title) here
logo: "/images/yogesTwitterRoundedResized_170.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mom . Ex-coder (never really stopped)<br><br>
  Currently in pre-sales technical consultancy<br><br>
  <br>Seeking opportunities to return to web development
  <br><br>
  A continuous and curious learner.
  <br><br>
  <a href="https://www.linkedin.com/in/yogeswarinarayasamy/" target="_blank">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://twitter.com/yogesnsamy" target="_blank">Connect with Me on Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142523611-1 # your Google Analytics tracking ID here
