title: Yogeswari Narayasamy # your name (or website title) here
logo: "/images/YogesResizedRounded.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mom, a professional coder for 7++ years once (best job ever!), presently in pre-sales tech consultancy close to eight years now, seeking opportunities to return to web development.
  <br><br>
  A continuous and curious learner.
  <br><br>
  <a href="https://www.linkedin.com/in/yogeswarinarayasamy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142523611-1 # your Google Analytics tracking ID here
