title: Yogeswari Narayasamy # your name (or website title) here
logo: "/images/yogesTwitterRoundedResized_170.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
<ul>
<li>Mom</li>
<li>Was a software developer for 7 years (never really stopped)</li>
<li>Currently in pre-sales technical consultancy</li>
<li>Seeking opportunities to return to web development</li>
</ul>
  <br><br>
  A continuous and curious learner.
  <br><br>
  <a href="https://www.linkedin.com/in/yogeswarinarayasamy/" target="_blank">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://twitter.com/yogesnsamy" target="_blank">Connect with Me on Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142523611-1 # your Google Analytics tracking ID here
