title: Yogeswari Narayasamy # your name (or website title) here
logo: "/images/Yoges_profile_picture_blueblack.jpg?raw=true" # your photo (or logo) here

  
theme: jekyll-theme-minimal
google_analytics: UA-142523611-1 # your Google Analytics tracking ID here

